### ISSUE TITLE
Missing clean-webpack-plugin module

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-a11y#36]
Added the following target to Cost Management

`"a11y-audit": "yarn patternfly-a11y -p https://stage.foo.redhat.com:1337/beta/openshift/cost-management --ignore-rules color-contrast -iI --crawl /",`

And encounter the 'clean-webpack-plugin' module error below.

<img width="867" alt="Screen Shot 2021-08-25 at 9 42 23 AM" src="https://user-images.githubusercontent.com/17481322/130801779-fd1d672a-0bc9-4bff-9706-33ccba506977.png">

**Comment by jschuler** [comment]
Should no longer be an issue
